title: ITU Operational Bulletin online
# the subpath of your site, e.g. /blog
baseurl: ""
# the base hostname & protocol for your site, e.g. http://example.com
url: "https://www.ituob.org"

ob_root: 'data/issues'

google_analytics: G-L3TCVBGNJ0

# TODO: Move to itu-ob-data
message_types:
  custom: {}
  amendment: {}

  misc_communications:
    title:
      en: Other communications

  mid:
    title:
      en: Maritime Identification Digits

  ipns:
    recommendation: { body: ITU-T, code: E.212, version: 2016-09 }
    title:
      en: International Identification Plan for Public Networks and Subscriptions

  org_changes:
    title:
      en: Changes in Administrations/ROAs and other entities or Organizations

  running_annexes:
    title:
      en: Lists annexed to the ITU Operational Bulletin
      ru: Списки, прилагаемые к Оперативному бюллетеню МСЭ
      zh: "国际电联《操作公报》后附的清单"

  approved_recommendations:
    title:
      en: Approval of ITU-T Recommendations
      ru: Утверждение Рекомендаций МСЭ-T
      zh: 批准ITU-T建议书

  sanc:
    recommendation: { body: ITU-T, code: Q.708, version: 1999-03 }
    title:
      en: Assignment of Signalling Area/Network Codes (SANC)
      ru: (TBD sanc-ru)
      zh: (TBD sanc-zh)

  iptn:
    recommendation: { body: ITU-T, code: E.164, version: 2010-11 }
    title:
      en: The International Public Telecommunication Numbering Plan
      ru: Международный план нумерации электросвязи общего пользования
      zh: 国际公众电信编号方案

  telephone_service:
    recommendation: { body: ITU-T, code: E.164 }
    url: http://www.itu.int/itu-t/inr-nnp
    title:
      en: Telephone Service
      ru: Услуга телефонной связи
      zh: 电话业务

  telephone_service_2:
    recommendation: { body: ITU-T, code: E.164 }
    url: http://www.itu.int/itu-t/inr-nnp
    title:
      en: Telephone Service
      ru: Услуга телефонной связи
      zh: 电话业务

  service_restrictions:
    url: http://www.itu.int/pub/T-SP-SR.1-2012
    title:
      en: Service Restrictions
      ru: Ограничения обслуживания
      zh: 业务限制

  callback_procedures:
    url: http://www.itu.int/pub/T-SP-PP.RES.21-2011/
    title:
      en: "Call-back and alternative calling procedures (Res. 21 Rev. PP-2006)"
      ru: "Обратный вызов и альтернативные процедуры вызова (Рез. 21 (Пересм. ПК-06))"
      zh: "回叫和迂回呼叫程序（2006年全权代表大会修订的第21号决议）"

languages:
  - id: en
    title: English
  - id: ru
    title: Russian
  - id: zh
    title: Chinese

default_language: en

collections:
  docs:
    output: true

in_app_help:
  app_name: "ITU OB Editor"
  in_collection: docs
  url_prefix: /_app_help/

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Makefile
  - monitor.sh
  - README.adoc
  - babel.config.js
  - package.json
  - package-lock.json
